name: inmobiliaria
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Añadir esta línea
    sdk: flutter         # Añadir esta línea
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.0.0
  mysql1: ^0.20.0
  logging: ^1.3.0
  intl: ^0.19.0 # Ajustado para compatibilidad con flutter_localizations
  image_picker: ^1.0.5
  path: ^1.8.3
  path_provider: ^2.1.1
  # Procesamiento de imágenes
  image: ^4.1.3     # Para procesamiento y manipulación de imágenes
  flutter_image_compress: ^2.1.0  # Para compresión más eficiente de imágenes
  uuid: ^4.3.3      # Para generar identificadores únicos para archivos
  
  # Dependencias para caché de imágenes
  cached_network_image: ^3.3.0  # Para caché de imágenes de red
  crypto: ^3.0.3                # Para generar claves hash para caché
  flutter_cache_manager: ^3.3.1 # Para gestión avanzada de caché
  shared_preferences: ^2.2.2    # Para persistencia de referencias de caché
  
  # Almacenamiento estructurado (opcional pero recomendado)
  hive: ^2.2.3                  # Almacenamiento NoSQL ligero y rápido
  hive_flutter: ^1.1.0          # Integración de Hive con Flutter
  photo_view: ^0.15.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  flutter_riverpod: ^2.6.1
  fl_chart: ^0.70.2
  mysql_client: ^0.0.27
  synchronized: ^3.3.1
  
  # Reemplazando file_picker con file_selector (más estable)
  file_selector: ^1.0.3  # API unificada para selección de archivos en todas las plataformas
  file_selector_android: ^0.5.0
  file_selector_ios: ^0.5.3+1  # Versión corregida según la sugerencia
  file_selector_linux: ^0.9.2
  file_selector_macos: ^0.9.3+1
  file_selector_windows: ^0.9.3
  
  pdf: ^3.10.7                  # Para generar y manipular PDFs
  printing: ^5.11.1             # Para vista previa e impresión de PDFs
  open_file: ^3.5.10
  month_picker_dialog: ^6.0.2 # Usar la versión sugerida
  share_plus: ^7.2.1          # Para compartir archivos y texto entre aplicaciones
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Para generación de adaptadores Hive (opcional)
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf